### PR TITLE
Add FileHandler class

### PR DESCRIPTION
**Pull request by tekktrik**
I needed to implement this class for keeping logs on an SD card I was already needed for file storage, I thought it might be a good addition to the library as a LoggingHandler

### CODE REVIEW

**Comment by gamblor21** [comment]
@tekktrik do you know how to resolve the merge conflict / need any help with that?

**Comment by tekktrik** [comment]
I'd love some help with that actually!

**Comment by gamblor21** [comment]
> I'd love some help with that actually!

I tried to merge it on the command line and I got an error about permissions. Not quite sure how to resolve this.
@kattni do you know who can help with this merge?

**Comment by kattni** [comment]
@gamblor21 You should be able to! I thought anyway. There's usually a checkbox that says "Allow edits from maintainers" or some such, but I don't see that here (possibly because I have higher perms than that box applies to so I don't see it on someone else's PR). The CircuitPythonLibrarians have write access to the repo, so it must be an issue on the PR itself. I should be able to help though! Do you have the changes somewhere I can get to so I can try to commit to this PR?

**Comment by kattni** [comment]
@gamblor21 I tried following the command line instructions that GitHub provides, and it appears to want to push to `main` which doesn't seem right. I thought it would involve updating something and pushing to this PR. I didn't complete the list of instructions - I stopped at `git push origin main`.

**Comment by kattni** [comment]
@gamblor21 Yeah, the command line instructions provides are intended for @tekktrik to run, and expects permission to push to tekktrik's repository. I am getting the same results as you. We either need to figure out pushing to the PR, getting permissions from tekktrik to access their fork, or walking tekktrik through the process so they can complete it themselves. Dealer's choice!

**Comment by gamblor21** [comment]
@tekktrik do you see beside the greyed out "Merge pull request" there is a link about _command line instructions_? Can you click on that (it will expand) try to follow those?

**Comment by tekktrik** [comment]
Maybe I'm looking in the wrong place, but what I'm seeing is a grayed out box to resolve conflicts, but that I don't have the write access to do so.  Should I be looking somewhere else?

Photo attached.

[
GithubSnapshot
](url)

**Comment by kattni** [comment]
@tekktrik You're not looking in the wrong place - apparently GitHub doesn't provide you with the command line instructions. I am attaching a screenshot here. Hopefully this helps.

Screen Shot 2021-10-31 at 16 51 51
e.

**Comment by tekktrik** [comment]
Just followed the instructions, did that help?

**Comment by tekktrik** [comment]
Do I need to create a new PR, or should I merge my new branch into this one that already has a PR?

**Comment by tekktrik** [comment]
Okay, I merged my local main branch into the one here with the PR, which is commit 9fd0bc8, does that fix it?

**Comment by gamblor21** [comment]
> Okay, I merged my local main branch into the one here with the PR after the instructions, which is commit [9fd0bc8](https://github.com/adafruit/Adafruit_CircuitPython_Logging/commit/9fd0bc8aad88d4a13cc118aa4c54249987e4561a), does that fix it?

No it is still showing the error. This is beyond my (limited) github experience, maybe someone else knows more who can help with it more.

**Comment by tekktrik** [comment]
I'm also happy to give access to my repo if that makes life easier :)

**Comment by gamblor21** [comment]
> I'm also happy to give access to my repo if that makes life easier :)

You can give me access to it if you want and I can try it that way again.

**Comment by tekktrik** [comment]
I should have given you access, but I haven't ever done that before, let me know if I didn't.

**Comment by gamblor21** [comment]
> I should have given you access, but I haven't ever done that before, let me know if I didn't.

That worked. I think I see the issue. You will have to pull the latest changes from the adafruit/main branch as your fork/branch has conflicts with the main one. You can set the remote with a command like `git remote add adafruit git@github.com:adafruit/Adafruit_CircuitPython_Logging.git` and then run `git fetch adafruit` and then you will have to rebase your code to the main branch `git rebase adafruit/main`.

I also saw this option in the github UI that may help.
image

Another option I can think of if this rebase seems large. Update your fork to the latest from adafruit and then reapply your changes in a new branch.

**Comment by tekktrik** [comment]
Got it!  Thank you so much @gamblor21 and @kattni!!

**Comment by gamblor21** [comment]
> Got it! Thank you so much @gamblor21 and @kattni!!

Thanks for sticking with it!

**Pull request merged**
